# Generated by Django 3.0.7 on 2020-08-20 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='residencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid.Municipio'),
        ),
        migrations.DeleteModel(
            name='Residencia',
        ),
    ]
